#!/usr/bin/env python3
"""
extract.py — Round 1 structured field extraction from full-text PDFs
══════════════════════════════════════════════════════════════════════

WHAT THIS SCRIPT DOES
─────────────────────
This is Step 4a of the SoK pipeline (Round 1 extraction).

For each paper in corpus_final.json it:
  1. Reads the plain-text version from _txt/<filename>.txt
     (generated by Poppler's pdftotext — see TEXT EXTRACTION below)
  2. Applies keyword regex dictionaries to extract structured fields
  3. Saves results to _extracted.json
  4. That JSON feeds build_xlsx.py to produce the extraction workbook.

The keyword dictionaries cover the 7 core SoK dimensions:
  • AI Tool used
  • Assessment Type
  • Education Context / Level
  • Study Design
  • Sample characteristics
  • Outcome metrics
  • Key technique flags (auto-grading, integrity detection, feedback gen, etc.)

TEXT EXTRACTION (Poppler, first 6 pages)
─────────────────────────────────────────
Before running this script, generate plain-text files with Poppler pdftotext:

    mkdir -p _txt
    for f in _pdfs/*.pdf; do
        pdftotext -l 6 "$f" "_txt/$(basename "${f%.pdf}").txt"
    done

  macOS:  brew install poppler
  Ubuntu: sudo apt install poppler-utils

WHY 6 PAGES?
  Abstract + introduction + methods sections typically appear in the first
  6 pages. Key classification signals (AI tool, study design, sample size)
  are almost always present by page 6. Using fewer pages speeds up processing
  and reduces noise from references sections.

ROUND 1 vs ROUND 2 DIFFERENCES
────────────────────────────────
  Round 1 (this file):    Poppler pdftotext  |  first 6 pages   |  12,000 chars
  Round 2 (extract_alt):  pypdf PdfReader    |  first 12 pages  |  20,000 chars

  Round 1 uses AI-tool-first tier policy (AI tool identity → classify tier).
  Round 2 uses assessment-type-first tier policy (assessment → classify tier).
  Disagreements between runs are flagged in build_alt_and_verify.py.

OUTPUT: _extracted.json
  [{
    "filename":      "2024_...",
    "title":         "...",
    "year":          "2024",
    "doi":           "10.1109/...",
    "AI_Tool":       "ChatGPT, GPT-4",
    "Assessment_Type":"Automated Grading, Academic Integrity",
    "Edu_Context":   "Computer Science, Higher Education",
    "Study_Design":  "Quasi-experimental",
    "Sample_Size":   "n=120 students",
    "Edu_Level":     "Undergraduate",
    "Outcomes":      "Accuracy 87.3%, Inter-rater kappa 0.82",
    "Technique_Flags":"[AutoGrading][IntegrityDetect]",
    "Dataset_Mentioned":"",
    "Country_Signals":"",
    "Notes":         ""    ← fill manually in build_xlsx.py workbook
  }, ...]

USAGE
─────
  python3 extract.py
  python3 extract.py --corpus path/to/corpus_final.json
  python3 extract.py --txt-dir path/to/_txt
══════════════════════════════════════════════════════════════════════
"""

import argparse
import json
import os
import re
from pathlib import Path

HERE         = Path(__file__).parent
CORPUS_JSON  = HERE / "corpus_final.json"
TXT_DIR      = HERE / "_txt"
EXTRACTED    = HERE / "_extracted.json"

# ─── character window for Round 1 ────────────────────────────────────────────
TEXT_WINDOW = 12_000   # first 12,000 chars of extracted text

# ═══════════════════════════════════════════════════════════════════════════════
# KEYWORD DICTIONARIES
# Each dictionary maps a label → regex pattern.
# tag_set() searches for all matching labels and returns them comma-separated.
# ═══════════════════════════════════════════════════════════════════════════════

# ── Dimension 1: AI Tool ─────────────────────────────────────────────────────
# Round 1 tier policy: AI tool identity drives the primary classification.
# We match the most specific tool first (GPT-4 before generic GPT).
AI_TOOL = {
    "ChatGPT":         r"\bChatGPT\b",
    "GPT-4":           r"\bGPT-?4\b",
    "GPT-3.5":         r"\bGPT-?3\.5\b",
    "GPT (generic)":   r"\bGPT\b(?!-\d)",
    "GitHub Copilot":  r"\bGitHub\s+Copilot\b",
    "Copilot":         r"\bCopilot\b(?!\s+[Ss]tudent)",
    "Gemini":          r"\bGemini\b",
    "Claude":          r"\bClaude\s+(?:AI|[23]|Opus|Sonnet|Haiku|3\.5)\b",
    "Llama":           r"\bLLaMA?[-\s]*\d*\b",
    "Bard":            r"\bBard\b",
    "Codex":           r"\bCodex\b",
    "PaLM":            r"\bPaLM\b",
    "Mistral":         r"\bMistral\b",
    "BERT":            r"\bBERT\b",
    "LLM (generic)":   r"\b(?:LLM|large\s+language\s+model)\b",
    "Generative AI":   r"\b(?:generative\s+AI|GenAI|foundation\s+model)\b",
    "Other AI":        r"\b(?:GPT\s+API|OpenAI\s+API|Anthropic\s+API)\b",
}

# ── Dimension 2: Assessment Type ─────────────────────────────────────────────
ASSESSMENT_TYPE = {
    "Automated Grading":     r"\b(?:auto\w*\s+grad\w+|auto\w*\s+scor\w+|AI[- ]?grad\w+|machine\s+grad\w+)\b",
    "Academic Integrity":    r"\b(?:academic\s+integrit\w+|plagiar\w+|cheating|academic\s+(?:dishonest|misconduct))\b",
    "AI Detection":          r"\b(?:AI.detect\w+|detect\w+\s+AI.generated|ChatGPT.detect\w+|watermark\w+)\b",
    "Feedback Generation":   r"\b(?:feedback\s+generat\w+|AI.?feedback|automated\s+feedback|personali[sz]ed\s+feedback)\b",
    "Formative Assessment":  r"\bformative\s+assess\w+\b",
    "Summative Assessment":  r"\bsummative\s+assess\w+\b",
    "Exam Generation":       r"\b(?:exam\s+generat\w+|question\s+generat\w+|quiz\s+generat\w+|test\s+item\s+generat\w+)\b",
    "Rubric Evaluation":     r"\b(?:rubric|scoring\s+rubric|assessment\s+rubric|grading\s+rubric)\b",
    "Peer Assessment":       r"\bpeer\s+assess\w+\b",
    "Self Assessment":       r"\bself.?assess\w+\b",
    "Performance Analysis":  r"\b(?:student\s+performance\s+(?:analy|predict|evaluat)|learning\s+analytic)\b",
    "Code Assessment":       r"\b(?:code\s+(?:review|evaluat|assess|grad)|programming\s+assign\w+\s+grad)\b",
}

# ── Dimension 3: Education Context / Discipline ───────────────────────────────
EDU_CONTEXT = {
    "Engineering Education":     r"\bengineering\s+(?:education|student|course|program|curriculum|class)\b",
    "Computer Science":          r"\b(?:computer\s+science|CS\s+education|CS[12]\b|computing\s+education)\b",
    "STEM Education":            r"\bSTEM\s+(?:education|student|course|class|program)\b",
    "Programming Education":     r"\b(?:programming\s+(?:course|education|class|assign)|intro\w*\s+to\s+programming)\b",
    "Software Engineering Edu":  r"\bsoftware\s+engineering\s+(?:education|course|class|curriculum)\b",
    "Technology Education":      r"\btechnology\s+education\b",
    "Electrical Engineering":    r"\belectrical\s+engineering\s+(?:education|course|student)\b",
    "Data Science Education":    r"\bdata\s+science\s+(?:education|course|curriculum)\b",
    "Cybersecurity Education":   r"\bcybersecurity\s+(?:education|course|curriculum)\b",
}

# ── Dimension 4: Study Design ────────────────────────────────────────────────
STUDY_DESIGN = {
    "Controlled Experiment":  r"\b(?:RCT|randomized\s+controlled|controlled\s+(?:trial|experiment)|experiment\w+\s+design)\b",
    "Quasi-experimental":     r"\b(?:quasi.?experiment\w+|pre.?post\s+test|pretest.?posttest)\b",
    "Survey":                 r"\b(?:survey\s+(?:study|method)|questionnaire|likert\s+scale)\b",
    "Case Study":             r"\b(?:case\s+study|classroom\s+(?:study|experiment))\b",
    "Mixed Methods":          r"\bmixed\s+(?:method|approach)\b",
    "Qualitative":            r"\b(?:qualitative\s+(?:study|method|research|analys)|interview\s+(?:study|data)|focus\s+group|thematic\s+analys)\b",
    "Literature Review":      r"\b(?:literature\s+review|systematic\s+review|SLR\b|meta.?analy|scoping\s+review)\b",
    "Design & Development":   r"\b(?:design\s+(?:science|and\s+develop)|tool\s+develop|system\s+(?:design|develop|implement))\b",
    "Conceptual/Theoretical": r"\b(?:conceptual\s+(?:paper|framework|study)|theoretical\s+(?:paper|framework)|framework\s+propos)\b",
    "Benchmark / Evaluation": r"\b(?:benchmark\w+|comparative\s+(?:study|evaluation)|evaluat\w+\s+(?:LLM|GPT|model\s+performance))\b",
}

# ── Dimension 5: Education Level ─────────────────────────────────────────────
EDU_LEVEL = {
    "Undergraduate":  r"\b(?:undergraduate|UG\b|bachelor|first.?year\s+student|introductory\s+course)\b",
    "Graduate":       r"\b(?:graduate\s+student|postgraduate|master.?s?\s+(?:student|program)|PhD\s+student|doctoral)\b",
    "Higher Education (unspecified)": r"\b(?:university\s+student|college\s+student|higher\s+education)\b",
    "K-12":           r"\b(?:K.?12|high\s+school\s+student|secondary\s+school|middle\s+school\s+student)\b",
}

# ── Dimension 6: Technique Flags (binary presence/absence) ───────────────────
TECHNIQUE_FLAGS = {
    "AutoGrading":        r"\b(?:auto\w*\s+grad|automated\s+grad|AI.?grading|machine\s+grad)\b",
    "IntegrityDetect":    r"\b(?:integrity\s+detect|plagiar\w+\s+detect|AI.detect\w+|cheat\w+\s+detect)\b",
    "FeedbackGen":        r"\b(?:feedback\s+gen\w+|AI.?feedback\s+gen\w+|automated\s+feedback)\b",
    "ExamQGen":           r"\b(?:question\s+gen\w+|exam\s+gen\w+|quiz\s+gen\w+|test\s+item\s+gen\w+)\b",
    "CodeReview":         r"\b(?:code\s+review|code\s+evaluat|programming\s+assign\w+\s+grad)\b",
    "StudentPerception":  r"\b(?:student\s+percep|student\s+attitud|student\s+satisfac|student\s+view\w+)\b",
    "FacultyPerception":  r"\b(?:faculty\s+percep|instructor\s+percep|teacher\s+percep|instructor\s+view)\b",
    "PolicyFramework":    r"\b(?:policy\s+(?:guid|frame|recommend)|academic\s+policy|institutional\s+guid|ethical\s+guid\w+\s+AI)\b",
    "LLM_Benchmark":      r"\b(?:benchmark\w+\s+(?:LLM|GPT)|GPT.?\d+\s+performance|model\s+comparison|evaluat\w+\s+LLM)\b",
}

# ── Dimension 7: Country / Region signals ────────────────────────────────────
COUNTRY = {
    "USA":         r"\b(?:United\s+States|U\.S\.A?\.?|American\s+university|US\s+university)\b",
    "UK":          r"\b(?:United\s+Kingdom|U\.K\.|British\s+university)\b",
    "Australia":   r"\b(?:Australia\w*|Australian\s+university)\b",
    "China":       r"\b(?:China|Chinese\s+university|Mainland\s+China)\b",
    "Germany":     r"\b(?:Germany|German\s+university|Deutschland)\b",
    "Malaysia":    r"\b(?:Malaysia\w*)\b",
    "South Korea": r"\b(?:South\s+Korea|Korean\s+university)\b",
    "Taiwan":      r"\b(?:Taiwan\w*)\b",
    "India":       r"\b(?:India\w*|Indian\s+university|IIT\b|NIT\b)\b",
    "Canada":      r"\b(?:Canada\w*|Canadian\s+university)\b",
    "Spain":       r"\b(?:Spain|Spanish\s+university|España)\b",
}

# ── Sample size extraction ────────────────────────────────────────────────────
SAMPLE_RE = re.compile(
    r"(?:"
    r"n\s*=\s*(\d+)"                         # n=120
    r"|(\d+)\s+student\w*\s+(?:participated|enrolled|completed|were\s+(?:recruited|selected))"
    r"|sample\s+(?:size\s+)?(?:of\s+|was\s+)?(\d+)"
    r"|(\d+)\s+participant\w*"
    r")",
    re.I,
)

# ── Outcome metric extraction ─────────────────────────────────────────────────
ACCURACY_RE = re.compile(
    r"\b(?:accuracy|precision|recall|F1.?score|AUC|BLEU|ROUGE)\s*"
    r"(?:of\s+|=\s*|:\s*|was\s+)?(\d{1,3}(?:\.\d+)?)\s*%?",
    re.I,
)
CORR_RE = re.compile(
    r"\b(?:pearson|spearman|cohen.?s?\s+kappa|inter.?rater\s+reliabil\w+|ICC)\b",
    re.I,
)
KAPPA_RE = re.compile(
    r"(?:kappa|Cohen.?s\s+kappa|ICC)\s*(?:=\s*|of\s+)?([0-9.]+)",
    re.I,
)


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def tag_set(text: str, kw_dict: dict) -> str:
    """Return comma-separated list of matching labels from kw_dict."""
    hits = [label for label, pat in kw_dict.items() if re.search(pat, text, re.I)]
    return ", ".join(hits)


def tag_flags(text: str, flag_dict: dict) -> str:
    """Return bracket-wrapped flags: [AutoGrading][FeedbackGen]..."""
    hits = [f"[{flag}]" for flag, pat in flag_dict.items() if re.search(pat, text, re.I)]
    return "".join(hits)


def extract_sample_size(text: str) -> str:
    """Extract the largest plausible sample size mentioned in the text."""
    matches = SAMPLE_RE.findall(text[:TEXT_WINDOW])
    numbers = [int(m) for group in matches for m in group if m and m.isdigit()]
    # Filter implausible values (< 5 or > 100,000)
    numbers = [n for n in numbers if 5 <= n <= 100_000]
    if not numbers:
        return ""
    return f"n={max(numbers)}"


def extract_outcomes(text: str) -> str:
    """Extract key outcome metric statements."""
    parts = []
    for m in ACCURACY_RE.finditer(text[:TEXT_WINDOW]):
        metric_text = m.group(0)
        if metric_text not in parts:
            parts.append(metric_text)
    if CORR_RE.search(text[:TEXT_WINDOW]):
        for m2 in KAPPA_RE.finditer(text[:TEXT_WINDOW]):
            parts.append(f"kappa/ICC={m2.group(1)}")
    return "; ".join(parts[:5])   # cap at 5 metric snippets


def extract_one(paper: dict, text: str) -> dict:
    """
    Extract all SoK fields from the text of one paper.
    text should be the Poppler plain-text output (first 6 pages).
    """
    t = text[:TEXT_WINDOW]

    # Round 1 tier policy: AI tool identity is the primary classifier.
    # We identify the MOST SPECIFIC tool mentioned first (GPT-4 > GPT-generic).
    ai_tool = tag_set(t, AI_TOOL)
    # If a specific model (GPT-4, ChatGPT) is found, drop the generic catch-all
    # labels to avoid noise in the matrix.
    if any(x in ai_tool for x in ["ChatGPT", "GPT-4", "GPT-3.5"]):
        ai_tool = re.sub(r",?\s*GPT \(generic\)", "", ai_tool).strip(", ")

    return {
        # ── identifier fields (from corpus_final.json) ──────────────────────
        "filename":        paper.get("filename", ""),
        "title":           paper.get("title", ""),
        "authors":         paper.get("authors", ""),
        "year":            paper.get("year", ""),
        "doi":             paper.get("doi", ""),
        "source":          paper.get("source", ""),
        "db_source":       paper.get("db_source", ""),
        # ── extracted SoK dimensions ─────────────────────────────────────────
        "AI_Tool":         ai_tool,
        "Assessment_Type": tag_set(t, ASSESSMENT_TYPE),
        "Edu_Context":     tag_set(t, EDU_CONTEXT),
        "Study_Design":    tag_set(t, STUDY_DESIGN),
        "Edu_Level":       tag_set(t, EDU_LEVEL),
        "Technique_Flags": tag_flags(t, TECHNIQUE_FLAGS),
        "Country":         tag_set(t, COUNTRY),
        # ── quantitative signals ─────────────────────────────────────────────
        "Sample_Size":     extract_sample_size(t),
        "Outcomes":        extract_outcomes(t),
        # ── blank for manual completion ──────────────────────────────────────
        "Notes":           "",
        "Manual_AI_Tool":  "",     # override if extraction is wrong
        "Manual_Design":   "",
        "Manual_Outcome":  "",
    }


def main():
    parser = argparse.ArgumentParser(description="Round 1 SoK field extraction (Poppler, 6 pages)")
    parser.add_argument("--corpus",  default=str(CORPUS_JSON), help="corpus_final.json")
    parser.add_argument("--txt-dir", default=str(TXT_DIR),     help="Directory of Poppler .txt files")
    parser.add_argument("--out",     default=str(EXTRACTED),   help="Output JSON path")
    args = parser.parse_args()

    print(f"\n{'═'*70}")
    print("  Round 1 Extraction — extract.py  (Poppler | 6 pages | 12,000 chars)")
    print(f"{'═'*70}\n")

    with open(args.corpus, encoding="utf-8") as f:
        corpus = json.load(f)

    txt_dir = Path(args.txt_dir)
    rows = []
    missing = []

    for paper in corpus:
        fn       = paper.get("filename", "")
        txt_path = txt_dir / fn.replace(".pdf", ".txt")

        if txt_path.exists():
            text = txt_path.read_text(encoding="utf-8", errors="replace")
        else:
            text = ""
            missing.append(fn)

        row = extract_one(paper, text)
        rows.append(row)

        ai   = row["AI_Tool"][:30] or "(none)"
        ass  = row["Assessment_Type"][:30] or "(none)"
        print(f"  {fn[:55]:<55}  AI={ai:<30}  Assess={ass}")

    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2, ensure_ascii=False)

    print(f"\n  Extracted {len(rows)} records → {args.out}")

    if missing:
        print(f"\n  WARNING: {len(missing)} PDFs had no .txt file:")
        for fn in missing[:10]:
            print(f"    {fn}")
        if len(missing) > 10:
            print(f"    ... and {len(missing)-10} more.")
        print(f"\n  Generate text files with:")
        print(f"    for f in _pdfs/*.pdf; do")
        print(f"      pdftotext -l 6 \"$f\" \"_txt/$(basename ${{f%.pdf}}).txt\"")
        print(f"    done")

    print(f"\n  NEXT STEP: python3 extract_alt.py  (Round 2)")
    print(f"  Then:      python3 build_xlsx.py")
    print(f"{'═'*70}\n")


if __name__ == "__main__":
    main()
