#!/usr/bin/env python3
"""
find_oa_springer.py — Find open-access PDF links for remaining Springer papers
Uses Unpaywall, Semantic Scholar, and CORE to find legal free versions.
Run locally (needs outbound HTTPS).

Usage:
    python3 find_oa_springer.py --email your@email.com
"""

import argparse, json, time, re
from pathlib import Path

import requests

HERE      = Path(__file__).parent
MANUAL    = HERE / "download_manual.json"
PDFS_DIR  = HERE / "_pdfs"
OA_SH     = HERE / "download_springer_oa.sh"

def publisher_of(doi):
    doi = (doi or "").lower()
    if "10.1007" in doi or "10.1057" in doi or "10.1186" in doi:
        return "springer"
    return "other"

def is_real_pdf(path):
    if not path.exists(): return False
    if path.stat().st_size < 10_000: return False
    with open(path, "rb") as f:
        return f.read(4) == b"%PDF"

def query_unpaywall(doi, email, session):
    try:
        r = session.get(
            f"https://api.unpaywall.org/v2/{doi}?email={email}",
            timeout=15)
        if r.status_code == 200:
            data = r.json()
            best = data.get("best_oa_location") or {}
            url  = best.get("url_for_pdf") or best.get("url")
            if not url:
                for loc in data.get("oa_locations", []):
                    url = loc.get("url_for_pdf") or loc.get("url")
                    if url: break
            return url
    except Exception:
        pass
    return None

def query_semantic_scholar(doi, session):
    try:
        r = session.get(
            f"https://api.semanticscholar.org/graph/v1/paper/DOI:{doi}"
            f"?fields=openAccessPdf,externalIds",
            timeout=15)
        if r.status_code == 200:
            data = r.json()
            oa = data.get("openAccessPdf")
            if oa and oa.get("url"):
                return oa["url"]
    except Exception:
        pass
    return None

def query_core(doi, session):
    try:
        r = session.get(
            f"https://api.core.ac.uk/v3/search/works?q=doi:{doi}&limit=1",
            timeout=15)
        if r.status_code == 200:
            results = r.json().get("results", [])
            if results:
                return results[0].get("downloadUrl") or results[0].get("fullTextLink")
    except Exception:
        pass
    return None

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--email", required=True)
    args = parser.parse_args()

    manual = json.loads(MANUAL.read_text())
    springer = [p for p in manual
                if publisher_of(p.get("doi","")) == "springer"
                and not is_real_pdf(PDFS_DIR / p.get("filename",""))]

    print(f"\n{'═'*70}")
    print(f"  Springer OA finder — {len(springer)} papers")
    print(f"{'═'*70}\n")

    session = requests.Session()
    session.headers.update({"User-Agent": f"SoK-Pipeline/1.0 ({args.email})"})

    found, not_found = [], []

    for i, p in enumerate(springer, 1):
        doi      = p.get("doi","").strip()
        title    = p.get("title","")[:65]
        filename = p.get("filename","")

        # Try sources in order
        url = query_unpaywall(doi, args.email, session)
        src = "unpaywall" if url else None
        time.sleep(0.5)

        if not url:
            url = query_semantic_scholar(doi, session)
            src = "s2" if url else None
            time.sleep(0.3)

        if not url:
            url = query_core(doi, session)
            src = "core" if url else None
            time.sleep(0.3)

        status = f"✓ [{src}]" if url else "✗"
        print(f"  [{i:>2}/{len(springer)}] {status}  {title}")

        if url:
            found.append({**p, "oa_url": url, "oa_source": src})
        else:
            not_found.append(p)

    # Write shell script for found papers
    lines = [
        "#!/usr/bin/env bash",
        "# download_springer_oa.sh — Free versions of Springer papers",
        "# Generated by find_oa_springer.py",
        "mkdir -p _pdfs", "",
    ]
    for rec in found:
        fn  = rec["filename"].replace("'", "\\'")
        url = rec["oa_url"].replace("'", "\\'")
        doi = rec.get("doi","")
        lines.append(f"# DOI: {doi}  source: {rec['oa_source']}")
        lines.append(f"wget -q --user-agent='Mozilla/5.0' -O '_pdfs/{fn}' '{url}' || \\")
        lines.append(f"  curl -sL -A 'Mozilla/5.0' -o '_pdfs/{fn}' '{url}'")
        lines.append(f"echo 'Done: {fn}'")
        lines.append("")

    OA_SH.write_text("\n".join(lines), encoding="utf-8")
    OA_SH.chmod(0o755)

    print(f"\n{'─'*70}")
    print(f"  OA versions found : {len(found)} / {len(springer)}")
    print(f"  Not found         : {len(not_found)}")
    print(f"\n  NEXT: bash download_springer_oa.sh")

    if not_found:
        print(f"\n  Still paywalled ({len(not_found)} papers):")
        for p in not_found:
            print(f"    {p.get('doi','')}  {p.get('title','')[:55]}")

    print(f"{'═'*70}\n")

if __name__ == "__main__":
    main()
