# ============================================================
# Pipeline 2 – Phase 1: Bibliometric Analysis
# Script 01: Load BIB files and build merged bibliometrix dataset
# ============================================================
# All five databases are included:
#   Scopus (1,001) and WoS (305) are loaded natively.
#   IEEE Xplore (278), ACM (999), ERIC (69) are first normalised
#   to Scopus-compatible BibTeX by 00_normalize_bib.py, then
#   loaded as a single file (ieee_acm_eric_normalized.bib).
#
# Run 00_normalize_bib.py before this script if the normalised
# file does not yet exist:
#   python3 pipeline2_analysis/bibliometrics/00_normalize_bib.py
#
# Input:  data/raw/scopus_1001.bib
#         data/raw/wos_305.bib
#         data/raw/ieee_acm_eric_normalized.bib   ← generated by Python
# Output: data/processed/bibliometrix_merged.rds
# ============================================================

library(bibliometrix)
library(tidyverse)
library(here)

RAW  <- here("data", "raw")
PROC <- here("data", "processed")

# ── 1. Load Scopus ───────────────────────────────────────────────────────────

message("Loading Scopus (1,001 records)...")
scopus <- tryCatch(
  convert2df(file.path(RAW, "scopus_1001.bib"),
             dbsource = "scopus", format = "bibtex"),
  error = function(e) { message("  Scopus error: ", e$message); NULL }
)
if (!is.null(scopus)) {
  scopus$DB_SOURCE <- "SCOPUS"
  message("  Loaded: ", nrow(scopus), " records")
}

# ── 2. Load Web of Science ───────────────────────────────────────────────────

message("Loading Web of Science (305 records)...")
wos <- tryCatch(
  convert2df(file.path(RAW, "wos_305.bib"),
             dbsource = "wos", format = "bibtex"),
  error = function(e) { message("  WoS error: ", e$message); NULL }
)
if (!is.null(wos)) {
  wos$DB_SOURCE <- "WOS"
  message("  Loaded: ", nrow(wos), " records")
}

# ── 3. Load normalised IEEE + ACM + ERIC ─────────────────────────────────────

norm_path <- file.path(RAW, "ieee_acm_eric_normalized.bib")
if (!file.exists(norm_path)) {
  message("⚠  Normalised BIB not found. Run 00_normalize_bib.py first.")
  ieee_acm_eric <- NULL
} else {
  message("Loading IEEE/ACM/ERIC normalised (1,342 records)...")
  ieee_acm_eric <- tryCatch(
    convert2df(norm_path, dbsource = "scopus", format = "bibtex"),
    error = function(e) { message("  IEEE/ACM/ERIC error: ", e$message); NULL }
  )
  if (!is.null(ieee_acm_eric)) {
    ieee_acm_eric$DB_SOURCE <- "IEEE_ACM_ERIC"
    message("  Loaded: ", nrow(ieee_acm_eric), " records")
  }
}

# ── 4. Merge and deduplicate all sources ─────────────────────────────────────

# bibliometrix sometimes returns list-type columns (e.g. JI) after merging.
# Coerce all list columns to character before every merge to avoid type clashes.
flatten_lists <- function(df) {
  df[] <- lapply(df, function(col) {
    if (is.list(col)) vapply(col, function(x) paste(x, collapse = "; "), character(1))
    else col
  })
  as.data.frame(df, stringsAsFactors = FALSE)
}

dfs <- Filter(Negate(is.null), list(scopus, wos, ieee_acm_eric))
if (length(dfs) == 0) stop("No data loaded — check BIB file paths and formats.")

message("Merging ", length(dfs), " source(s) with deduplication...")

# Step 1: try mergeDbSources for Scopus + WoS (the two it handles natively)
scopus_wos_dfs <- Filter(Negate(is.null), list(scopus, wos))
merged_sw <- tryCatch({
  m <- flatten_lists(scopus_wos_dfs[[1]])
  if (length(scopus_wos_dfs) == 2) {
    m <- mergeDbSources(m, flatten_lists(scopus_wos_dfs[[2]]),
                        remove.duplicated = TRUE)
  }
  m
}, error = function(e) {
  message("  Scopus+WoS merge failed: ", e$message, " — using rbind")
  all_cols <- unique(unlist(lapply(scopus_wos_dfs, names)))
  dfs_aligned <- lapply(scopus_wos_dfs, function(df) {
    df <- flatten_lists(df)
    df[setdiff(all_cols, names(df))] <- NA_character_
    df[all_cols]
  })
  do.call(rbind, dfs_aligned)
})
message("  Scopus + WoS: ", nrow(merged_sw), " records")

# Step 2: column-align and rbind all three sources
all_cols <- unique(unlist(lapply(c(list(merged_sw), Filter(Negate(is.null), list(ieee_acm_eric))), names)))
align_df <- function(df) {
  df <- flatten_lists(df)
  df[setdiff(all_cols, names(df))] <- NA_character_
  df[all_cols]
}
all_dfs <- c(list(merged_sw), Filter(Negate(is.null), list(ieee_acm_eric)))
merged_raw <- do.call(rbind, lapply(all_dfs, align_df))
message("  After rbind (pre-dedup): ", nrow(merged_raw), " records")

# Step 3: manual DOI + title deduplication
# Priority order: SCOPUS > WOS > IEEE_ACM_ERIC (Scopus records kept on conflict)
src_priority <- c("SCOPUS" = 1, "WOS" = 2, "IEEE_ACM_ERIC" = 3)
merged_raw$.priority <- src_priority[merged_raw$DB_SOURCE]
merged_raw$.priority[is.na(merged_raw$.priority)] <- 4
merged_raw <- merged_raw[order(merged_raw$.priority), ]

# Normalize DOI for matching
merged_raw$.doi_norm <- tolower(trimws(gsub("https?://doi\\.org/", "", merged_raw$DI)))
merged_raw$.doi_norm[merged_raw$.doi_norm == ""] <- NA

# Remove DOI duplicates (keep first = highest priority source)
doi_keep <- is.na(merged_raw$.doi_norm) | !duplicated(merged_raw$.doi_norm)
merged_dedup <- merged_raw[doi_keep, ]
n_doi_removed <- nrow(merged_raw) - nrow(merged_dedup)
message("  DOI duplicates removed: ", n_doi_removed)

# Normalize title for matching records without DOI
merged_dedup$.ti_norm <- tolower(gsub("[^a-z0-9]", "", merged_dedup$TI))
merged_dedup$.ti_norm[nchar(merged_dedup$.ti_norm) < 10] <- NA

title_keep <- is.na(merged_dedup$.ti_norm) | !duplicated(merged_dedup$.ti_norm)
merged <- merged_dedup[title_keep, ]
n_title_removed <- nrow(merged_dedup) - nrow(merged)
message("  Title duplicates removed: ", n_title_removed)

# Clean temp columns
merged$.priority  <- NULL
merged$.doi_norm  <- NULL
merged$.ti_norm   <- NULL

message("Records after merge + dedup: ", nrow(merged))

# ── 4. Filter to 2022–2026 ───────────────────────────────────────────────────

merged <- merged %>% filter(PY >= 2022, PY <= 2026)
message("Records in 2022–2026 window: ", nrow(merged))

# ── 5. Save ──────────────────────────────────────────────────────────────────

saveRDS(merged, file.path(PROC, "bibliometrix_merged.rds"))
message("Saved → data/processed/bibliometrix_merged.rds (", nrow(merged), " records)")
